version: '3.1'

services:

  tennis-mongo:
    image: mongo:7.0.17
    container_name: 'tennis-mongo'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: tennis
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      retries: 3
    networks:
      - tennis
    volumes:
      - tennis-mongo-data:/data/db

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      # Define the advertised listeners (internal and external)
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      # Define listeners' security protocol
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT  # Default security protocol for all listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT  # Define protocol for each listener
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092  # Expose both internal and external listeners
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE  # Define names for listeners
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_MODE: ZOOKEEPER
      # Define the inter-broker listener name
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE  # Choose INSIDE or OUTSIDE based on your needs
    ports:
      - "9092:9092"  # External access to Kafka (localhost:9092)
      - "9093:9093"  # Internal access to Kafka (kafka:9093)
    depends_on:
      - zookeeper

volumes:
  tennis-mongo-data:

networks:
  tennis:
    driver: bridge